### ISSUE TITLE
 I can't see the graph

### ISSUE THREAD

**Issue by rrpereira** [data-science-institute-nuig/D3-Tree-Graph#1]
Hello, 
First of all, thanks for your tutorials.

I have been trying to run this project but something is wrong. I am able to execute the local server inside the project's folder but when i open the page this is what i get:

![Selection_004](https://user-images.githubusercontent.com/36520545/120487021-7daa3f80-c3ad-11eb-9f06-594ea721ae30.png)

Do you have any idea what is happening? Thanks.

**Comment by carlostighe** [comment]
So there are two pages in the project. 
`index.html` which is the page that you are seeing 
`tree.html` which is what you want to see
click on the tree link or go to `localhost:8081/tree.html`

**Comment by rrpereira** [comment]
I guess it was some issue related with http-server. It's working now, thanks.

**Comment by carlostighe** [comment]
Glad its working
